/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package roaringutils;

public class DeadzoneUtils {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new DeadzoneUtils().getGreeting());
    }
}
