/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package roaringutils;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main() {
        System.out.println(new Main().getGreeting());
    }
    
}
